---
title: "ITS2 Symportal to phyloseq"
author: "Shayle Matsuda"
date: "6/27/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

This is a script taking the Symportal output and oragnizing it into phyloseq ready objects
* load in all data. Use the raw reads to view seqs and then create rarefied relative abundance df yourself
```{r}
#rm(list=ls())
library(dplyr)
library(readxl)
library(phyloseq)
library(janitor)
library("writexl")
library(tidyverse)

```

#Reading in data by ABSOLUTE abundances
Profiles Absolute
DIVs absolute
```{r} 
#add metadata to symportal submission data
sam0 <- readxl::read_xlsx("data/MCL_Symp_Metadata_20220621.xlsx") #Symportal metadata combined from above

#new col of C or D dominance
# Summarize by TagID to get total proportion of C and D in each colony
sam0_dom <- sam0 %>%
  group_by(TagID) %>%
  summarise(Total_C = sum(Prop.C, na.rm = TRUE),  # Sum proportions of C
            Total_D = sum(Prop.D, na.rm = TRUE)) %>%  # Sum proportions of D
  mutate(dom = ifelse(Total_C > Total_D, "C", "D"))  # Assign dominant clade

# Merge the 'dom' column back into the original dataframe
sam0 <- left_join(sam0, sam0_dom[, c("TagID", "dom")], by = "TagID")

sam1 <- as.matrix(sam0[, -1])
rownames(sam1) <- sam0$sample_name
sam <- sample_data(data.frame(sam1))

taxnames <- read_tsv(
  file  = "data/20201214_matsuda_MCL/post_med_seqs/133_20201216_DBV_20201216T011417.seqs.absolute.abund_only.txt",
  n_max = 0) %>%
  select(-1) %>%
  names(.)
tax0 <- data_frame(
  DIV = taxnames,
  clade = str_extract(DIV, "[A-Z]")
)
tax1 <- as.matrix(tax0)
rownames(tax1) <- tax0$DIV
tax <- tax_table(tax1)

otu0 <- read_tsv(
  file  = "data/20201214_matsuda_MCL/post_med_seqs/133_20201216_DBV_20201216T011417.seqs.absolute.abund_and_meta.txt") %>%
  select(-1, -(3:33))
otu1 <- as.matrix(otu0[, -1])
rownames(otu1) <- otu0$sample_name

otu <- otu_table(otu1, taxa_are_rows = FALSE)
DIVs <- phyloseq(otu, tax, sam)

sample_data(DIVs)$Prop.D <- as.numeric(sample_data(DIVs)$Prop.D)
sample_data(DIVs)$Prop.C <- as.numeric(sample_data(DIVs)$Prop.C)
sample_data(DIVs)$Location <- as.factor(sample_data(DIVs)$Location)
sample_data(DIVs)$TagID <- as.factor(sample_data(DIVs)$TagID)
sample_data(DIVs)$Depth.ft <- as.numeric(sample_data(DIVs)$Depth.ft)
sample_data(DIVs)$Samp.Date <- as.Date(sample_data(DIVs)$Samp.Date)
sample_data(DIVs)$Land_Ocean <- as.factor(sample_data(DIVs)$Land_Ocean)
sample_data(DIVs)$SampleNum <- as.factor(sample_data(DIVs)$SampleNum)
sample_data(DIVs)$LocSamp <- as.factor(sample_data(DIVs)$LocSamp)
sample_data(DIVs)$dom <- as.factor(sample_data(DIVs)$dom)

```
Save as an obj
```{r}
save( DIVs, file = "data/DIV_abs_2025.RData")
```


